version: "3.1"
services:
  mongo-service:
    ports:
      - 5000:5000
    networks:
      - chella
    image: 2chella/express-js
    restart: always
    volumes:
      - ./:/application/
    command:
      - npm
      - start
networks:
  chella:
    external: true
